sudo: false

language: php

php:
  - 7.2.10

before_script:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction --dev

notifications:
  email: lcosta_96@hotmail.com.br
  on_success: never
  on_failure: always

services:
  - postgresql
